### ISSUE TITLE
ebk moduel

### ISSUE THREAD

**Issue by andrewshrout** [m0dd0/RotatingUserAgentMiddleware#1]
`ebk.middlewares.RotatingUserAgentsMiddleware`

Hi - I was wondering what package this is? This module is missing, and I cannot find it anywhere.

**Comment by m0dd0** [comment]
This is the name of the crawler for which the middleware is applied. So you must change `ebk` to the name of your crawler. I just copy/pasted the settings from my project when writing the README. This should definitely be changed to something more obvious in the README.

**Comment by m0dd0** [comment]
fixed in 78b635985be9bd5a1712eaa4dd4b8870eca9137d
